# BFN Platform modules

BFN_PLATFORM_MODULE_VERSION = 1.1

export BFN_PLATFORM_MODULE_VERSION

BFN_PLATFORM_MODULE = sonic-platform-modules-bfn_$(BFN_PLATFORM_MODULE_VERSION)_amd64.deb
$(BFN_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn
$(BFN_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BFN_PLATFORM_MODULE)_PLATFORM = x86_64-accton_wedge100bf_65x-r0
SONIC_DPKG_DEBS += $(BFN_PLATFORM_MODULE)

BFN_SONIC_PLATFORM_API_PY2 = python-sonic-platform-bfn_1.0_amd64.deb
$(BFN_SONIC_PLATFORM_API_PY2)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn
$(BFN_SONIC_PLATFORM_API_PY2)_PLATFORM = x86_64-accton_wedge100bf_65x-r0
SONIC_PYTHON_STDEB_DEBS += $(BFN_SONIC_PLATFORM_API_PY2)

BFN_SONIC_PLATFORM_API_PY3 = python3-sonic-platform-bfn_1.0_amd64.deb
$(BFN_SONIC_PLATFORM_API_PY3)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn
$(BFN_SONIC_PLATFORM_API_PY3)_PLATFORM = x86_64-accton_wedge100bf_65x-r0
$(BFN_SONIC_PLATFORM_API_PY3)_PYTHON_VERSION = 3
SONIC_PYTHON_STDEB_DEBS += $(BFN_SONIC_PLATFORM_API_PY3)

BFN_PLATFORM_DEBS=$(BFN_PLATFORM_MODULE)\
	$(BFN_SONIC_PLATFORM_API_PY2)\
	$(BFN_SONIC_PLATFORM_API_PY3) 
