# BFN Platform modules

BFN_MONTARA_PLATFORM_MODULE_VERSION = 1.1

export BFN_MONTARA_PLATFORM_MODULE_VERSION

BFN_MONTARA_PLATFORM_MODULE = sonic-platform-modules-bfn-montara_$(BFN_MONTARA_PLATFORM_MODULE_VERSION)_amd64.deb
$(BFN_MONTARA_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn-montara
$(BFN_MONTARA_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BFN_MONTARA_PLATFORM_MODULE)_PLATFORM = x86_64-accton_wedge100bf_32x-r0
SONIC_DPKG_DEBS += $(BFN_MONTARA_PLATFORM_MODULE)

BFN_MONTARA_SONIC_PLATFORM_API_PY2 = python-sonic-platform-bfn-montara_1.0_amd64.deb
$(BFN_MONTARA_SONIC_PLATFORM_API_PY2)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn-montara
$(BFN_MONTARA_SONIC_PLATFORM_API_PY2)_PLATFORM = x86_64-accton_wedge100bf_32x-r0
SONIC_PYTHON_STDEB_DEBS += $(BFN_MONTARA_SONIC_PLATFORM_API_PY2)

BFN_MONTARA_SONIC_PLATFORM_API_PY3 = python3-sonic-platform-bfn-montara_1.0_amd64.deb
$(BFN_MONTARA_SONIC_PLATFORM_API_PY3)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-bfn-montara
$(BFN_MONTARA_SONIC_PLATFORM_API_PY3)_PLATFORM = x86_64-accton_wedge100bf_32x-r0
$(BFN_MONTARA_SONIC_PLATFORM_API_PY3)_PYTHON_VERSION = 3
SONIC_PYTHON_STDEB_DEBS += $(BFN_MONTARA_SONIC_PLATFORM_API_PY3)

BFN_MONTARA_PLATFORM_DEBS=$(BFN_MONTARA_PLATFORM_MODULE)\
	$(BFN_MONTARA_SONIC_PLATFORM_API_PY2)\
	$(BFN_MONTARA_SONIC_PLATFORM_API_PY3) 
